#############################################
# Module Validation backend global configuration file
#############################################

# Database
SQLALCHEMY_DATABASE_URI = "postgresql://geonatadmin:monpassachanger@localhost:5432/geonature242db"
URL_APPLICATION = 'http://127.0.0.1:4200'
API_ENDPOINT = 'http://127.0.0.1:8000'
API_TAXHUB = 'http://127.0.0.1:5000/api'

# Remplacer par une clé alétoire complexe
SECRET_KEY = 'super secret key'

# Code EPSG des geométries dans la BDD
LOCAL_SRID = '2154'

# Langue principale par défaut
DEFAULT_LANGUAGE='fr'


#######################################################################################
###### Si vous souhaitez surcoucher certains paramètres,
###### compléter les sections ci-dessous à partir du modèle default_config.toml.example
#######################################################################################

# Configuration liée aux ID de BDD
[BDD]

# Configuration générale du frontend
[FRONTEND]

# Mise en place d'un système d'erreur par email
[MAILERROR]

# Configuration de la Synthese
[SYNTHESE]
    # colonne des exports de la synthese
    [EXPORT_COLUMNS]










